### ISSUE TITLE
`needs` fails if you specify a release which has not been parsed yet

### ISSUE THREAD

**Issue by WoodyWoodsta** [helmfile/helmfile#323] opened 2022-08-25 15:45 UTC
### Operating system

macOS 12.5.1

### Helmfile Version

v0145.4

### Helm Version

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### Bug description

I have multiple helmfiles in my project. Some releases in those helmfiles "need" other releases. There is a singular helmfile at the root, which references helmfiles by means of the `helmfiles` configuration property.

If a release needs another which has not yet been reached, helmfile fails. This means I have to make sure I order the `helmfiles` in a specific way to get `needs` dependencies to work. With glob patterns, this is not possible, and sometimes it's logically impossible as there could be a non-trivial dependency tree.

In my mind (and I'm surprised it isn't this way) it seems as though helmfile needs to gather all releases and do the dependency resolution afterwards.

Have I misunderstood the use of `needs` or is this just a limitation of the implementation?

### Example helmfile.yaml

```yaml
# Root helmfile
helmfiles:
  - apps/*/helmfile.yml

---

# apps/myapp1/helmfile.yml
releases:
  - name: myapp1
    needs:
      - myapp2

---

# apps/myapp2/helmfile.yml
releases:
  - name: myapp2

```

### Error message you've seen (if any)

```
Error: in ./helmfile.yaml: in .helmfiles[0]: in apps/***/helmfile.yml: release(s) "***/***" depend(s) on an undefined release "***/***". Perhaps you made a typo in "needs" or forgot defining a release named "***" with appropriate "namespace" and "kubeContext"?
in ./helmfile.yaml: in .helmfiles[0]: in apps/***/helmfile.yml: release(s) "***/***" depend(s) on an undefined release "***/***". Perhaps you made a typo in "needs" or forgot defining a release named "networking" with appropriate "namespace" and "kubeContext"?
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by junnplus** [comment] 2022-08-27 13:02
I have the same confusion.

**Comment by junnplus** [comment] 2022-08-27 14:12
It seems to be related to the current implementation, a helmfile is used as a unit to perform checks

**Comment by yxxhero** [comment] 2022-08-27 23:31
@junnplus PR is welcome. Thanks very much.

**Comment by mumoshu** [comment] 2022-09-18 11:20
> If a release needs another which has not yet been reached, helmfile fails
> ...
> In my mind (and I'm surprised it isn't this way) it seems as though helmfile needs to gather all releases and do the dependency resolution afterwards.

@WoodyWoodsta I hear you, but it's working as intended as of today! Sub-helmfiles (helmfiles field) predates our DAG support (the needs field) and they are two completely different features.

What you can do instead in the meantime would be to hack the root helmfile.yaml with functions that "includes" arbitrary files as helmfile.yaml snippets, like `readFile` and `tpl`, so that all the releases defined in all the sub-helmfiles included would reside within the scope of the root helmfile.yaml, making those possible to be parts of the same DAG.

In this thread https://github.com/helmfile/helmfile/discussions/178#discussioncomment-3633997 we are talking about a potential enhancement to Helmfile for making sub-helmfiles a part of the DAG support.
It would be great if you could chime in there and provide any feedback!

**Comment by WoodyWoodsta** [comment] 2022-09-19 07:45
> they are two completely different features.

But a part of the same tool - the expectation is that features of the same tool work together.

Will have a read through the thread and comment if I think I can add anything.

**Comment by mumoshu** [comment] 2022-09-19 10:22
Yeah, I hear you! I'm just saying that it isn't trivial to design or implement.

Currently, each helmfile has its own scope and building a DAG across all the involved (sub-)helmfiles doesn't make sense from the author's perspective. So-

> In my mind (and I'm surprised it isn't this way) it seems as though helmfile needs to gather all releases and do the dependency resolution afterwards.

Although I totally understand your sentiment, this won't be implemented within or on top of any of our current `releases`, `helmfiles` or `bases`. I believe we need something else.

**Closed** 2022-10-10 12:03 UTC
Labels: enhancement, wontfix
