### ISSUE TITLE
0.145.0 fails to update deps for plain-YAML releases

### ISSUE THREAD

**Issue by evgkrsk** [helmfile/helmfile#207] opened 2022-07-04 12:18 UTC
### Operating system

MacOS 12.4

### Helmfile Version

v0.145.0

### Helm Version

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### Bug description

After upgrading helmfile 0.144 -> 0.145 (roboll->helmfile) it fails to run "deps" for plain-YAML releases (for chartify) . Rollback to 0.144 fixes problem.

### Example helmfile.yaml

```
releases:
- name: gitlab-rbac
  chart: ./helmfiles/gitlab-rbac # <- dir with plain yaml manifests
```

### Error message you've seen (if any)

```
err 3: command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: update (6 bytes)
  3: ./helmfiles/gitlab-rbac (23 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Chart.yaml file is missing

COMBINED OUTPUT:
  Error: Chart.yaml file is missing
```

### Steps to reproduce

Make helmfile.yaml for plain-yaml release, run "helmfile deps" for it

**Comment by yxxhero** [comment] 2022-07-05 00:11
`plain yaml manifests` not helm chart? @evgkrsk

**Comment by evgkrsk** [comment] 2022-07-05 03:27
Yes, helmfile can wrap directory with k8s manifests in helm release (via "chartify": https://github.com/roboll/helmfile/pull/673)

**Comment by evgkrsk** [comment] 2022-07-05 03:28
And 0.144 works fine with such directories for years.

**Comment by yxxhero** [comment] 2022-07-05 03:34
@evgkrsk do you use helm-x replace helm?

**Comment by evgkrsk** [comment] 2022-07-05 03:36
No, helmfile does it under the hood all this years...

**Comment by yxxhero** [comment] 2022-07-05 09:18
@mumoshu

**Comment by mumoshu** [comment] 2022-07-05 12:18
Thanks for reporting! Umm interesting. Can this be caused by the same issue fixed via https://github.com/helmfile/helmfile/pull/209?

**Comment by yxxhero** [comment] 2022-07-05 13:40
@evgkrsk I will check this.

**Closed** 2022-07-06 00:54 UTC
Labels: bug

**Comment by yxxhero** [comment] 2022-07-06 01:20
@evgkrsk new version released. Please enjoy it. Thanks very much. Thanks for your issue.

**Comment by evgkrsk** [comment] 2022-07-06 05:31
Thanks!
