### ISSUE TITLE
Various issues with Docker release 0.147.0 and `helmfile version`

### ISSUE THREAD

**Issue by pathob** [helmfile/helmfile#425] opened 2022-10-10 10:06 UTC
### Operating system

Docker

### Helmfile Version

0.147.0

### Helm Version

3.9.0

### Bug description

The latest Docker release for 0.147.0 (re-)introduces some issues.

First of all, the version (and the build date) is not defined anymore:

```
$ helmfile version

▓▓▓ helmfile

  Version              (devel)
  Git Commit           ad25755
  Build Date           N/A
  Commit Date          09 Oct 22 01:13 UTC (1 day ago)
  Dirty Build          no
  Go version           1.18
  Compiler             gc
  Platform             linux/amd64
```

Additionally, when used in our CI, the command ends with the following error:

```
$ helmfile version
...
Head "https://github.com/helmfile/helmfile/releases/latest": x509: certificate signed by unknown authority
```

A fix would be much appreciated.

Thanks, Patrick

### Example helmfile.yaml

Not needed

### Error message you've seen (if any)

See above

### Steps to reproduce

helmfile version

### Working Helmfile Version

0.146.0

**Comment by yxxhero** [comment] 2022-10-10 10:20
@pathob What can I do for you? Please show yours expect.

**Comment by pathob** [comment] 2022-10-10 10:24
Thanks for the hint. Besides that:

Version should show the correct version number as already written above :)

**Comment by mumoshu** [comment] 2022-10-10 11:04
@pathob Hey! Thanks for reporting. We're going to fix the version number embedding thing in #427.
In addition, I'm also concerned about the `certificate signed by unknown authority` error you saw. Perhaps it's related to some missing CA certs in your image? Just to be clear, which docker image variant are you using, ubutun, debian, or alpine-based one?

**Comment by pathob** [comment] 2022-10-10 11:18
@mumoshu Same error in all images. Might be related to the fact that I try to run it in a regulated environment, most likely no internet access to github.com

**Comment by mumoshu** [comment] 2022-10-10 11:23
@pathob Thanks. That might be the cause as I couldn't reproduce it with any of the available 0.147.0 images.
You still need to set `HELMFILE_UPGRADE_NOTICE_DISABLED` to a non-empty value even if we merged #427.
Can you deal with it? We haven't really designed the image to be used as-is within a regulated environment so in that sense I can say it isn't a breaking change.
But I do want to hear your opinion or thoughts on it.

**Comment by pathob** [comment] 2022-10-10 11:43
`HELMFILE_UPGRADE_NOTICE_DISABLED` solves the issue for me.

It's okay if the image is not perfectly designed for regulated environment, I just hope that helmfile in general is and stays like that :)

**Comment by mumoshu** [comment] 2022-10-10 12:23
@pathob Thank you for your confirmation! We'll do our best to keep it runtime-environment agnostic.

**Comment by yxxhero** [comment] 2022-10-10 13:39
@mumoshu @pathob I will close this issue.

**Closed by yxxhero** 2022-10-10 13:39 UTC
